//! povray support for vegas-lattice-rs.

use std::io::Write;

use crate::{Lattice, error::Result};

pub fn to_povray<W: Write>(writer: &mut W, lattice: &Lattice) -> Result<()> {
    writeln!(writer, "// Generated by vegas-lattice-rs")?;
    writeln!(writer, "#version 3.7")?;
    writeln!(writer, "global_settings {{ assumed_gamma 1.0 }}")?;
    let (sx, sy, sz) = lattice.size();
    let (cx, cy, cz) = (sx / 2.0, sy / 2.0, sz / 2.0);
    writeln!(
        writer,
        "camera {{ location <{}, {}, {}> look_at <{}, {}, {}> }}",
        2.0 * sx,
        2.0 * sy,
        5.0 * sz,
        cx,
        cy,
        cz
    )?;

    writeln!(
        writer,
        "light_source {{ <{}, {}, {}> color rgb <1.0, 1.0, 1.0> }}",
        cx,
        cy,
        2.0 * sz
    )?;
    writeln!(
        writer,
        "light_source {{ <{}, {}, {}> color rgb <1.0, 1.0, 1.0> }}",
        cx,
        cy,
        -2.0 * sz
    )?;

    for site in lattice.sites() {
        let (x, y, z) = site.position();
        writeln!(
            writer,
            "sphere {{ <{}, {}, {}>, 0.25 pigment {{ color rgb <0.5, 0.1, 0.8> }} finish {{ specular 0.6 roughness 0.3 }} }}",
            x, y, z
        )?;
    }
    Ok(())
}
